events {
  worker_connections 1024;
}

http {
  upstream backend {
    server localhost:5000;
  }
  upstream landing {
    server localhost:3000;
  }
  upstream vendor {
    server localhost:5174;
  }
  upstream admin {
    server localhost:5175;
  }
  upstream storefront {
    server localhost:5176;
  }

  server {
    listen 80;
    server_name localhost;

    location /api/ {
      proxy_pass http://backend/api/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location / {
      proxy_pass http://landing/;
    }

    location /vendor/ {
      proxy_pass http://vendor/;
    }

    location /admin/ {
      proxy_pass http://admin/;
    }

    location /store/ {
      proxy_pass http://storefront/;
    }
  }
}
